/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package consecionario.Formularios;

import BD.CatalogoBD;
import consecionario.CatalogoCarros;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author Finot
 */
public class CatalogoHatchback extends javax.swing.JPanel {

     
    
    
     

     public void SetImageLabel (JLabel labelName, String resourcePath){
        
        java.net.URL imgURL = getClass().getResource(resourcePath);
        if (imgURL == null) {
        System.err.println("No se encontró la imagen en: " + resourcePath);
        return;
    }
        ImageIcon imageIcon = new ImageIcon(imgURL);
        Image scaledImage = imageIcon.getImage().getScaledInstance(
        labelName.getWidth(),
        labelName.getHeight(),
        Image.SCALE_SMOOTH
    );

    labelName.setIcon(new ImageIcon(scaledImage));
}
    
     //inicializa el metodo para cargar la imagen deceada en el label decignado
    public void CargarImagen(){
      CatalogoBD catalogoBD = new CatalogoBD();
    List<CatalogoCarros> lista = catalogoBD.obtenerPorCategoria("Hatchback");

    if (lista.isEmpty()) {
        System.out.println("No se encontraron autos hatchback.");
        return;
    }

    // Establece máximo de 3 imágenes
    if (lista.size() >= 1) {
        SetImageLabel(txtImagen1, lista.get(0).getImagen());
        txtCaracteristicas1.setText("<html>" + lista.get(0).getDescripcion() + "</html>");
    }

    if (lista.size() >= 2) {
        SetImageLabel(txtImagen2, lista.get(1).getImagen());
        txtCaracteristicas2.setText("<html>" + lista.get(1).getDescripcion() + "</html>");
    }

    if (lista.size() >= 3) {
        SetImageLabel(txtImagen3, lista.get(2).getImagen());
        txtCaracteristicas3.setText("<html>" + lista.get(2).getDescripcion() + "</html>");
    }

       
    }
    
    
    /**
     * Creates new form CatalogoHatchback
     */
    public void VentanaInicio(){
        
        JPanelVentana3.setVisible(false);
        JPanelVentana1.setVisible(true);
        JPanelVentana2.setVisible(false); 
        
    }
    public CatalogoHatchback() {
        initComponents();
          
        txtImagen1.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            CargarImagen();
            VentanaInicio(); 
        }
    });
         
    }
   /* 
    /*
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        JPanelVentana3 = new javax.swing.JPanel();
        txtImagen3 = new javax.swing.JLabel();
        btnSiguienteV3 = new javax.swing.JButton();
        txtCaracteristicas3 = new javax.swing.JLabel();
        JPanelVentana2 = new javax.swing.JPanel();
        txtImagen2 = new javax.swing.JLabel();
        btnSiguienteV2 = new javax.swing.JButton();
        txtCaracteristicas2 = new javax.swing.JLabel();
        JPanelVentana1 = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        txtCaracteristicas1 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        txtImagen1 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(500, 199));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtImagen3.setText("Coche");

        btnSiguienteV3.setText("Siguiente");
        btnSiguienteV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteV3ActionPerformed(evt);
            }
        });

        txtCaracteristicas3.setText("jLabel1");

        javax.swing.GroupLayout JPanelVentana3Layout = new javax.swing.GroupLayout(JPanelVentana3);
        JPanelVentana3.setLayout(JPanelVentana3Layout);
        JPanelVentana3Layout.setHorizontalGroup(
            JPanelVentana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelVentana3Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(JPanelVentana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelVentana3Layout.createSequentialGroup()
                        .addComponent(btnSiguienteV3)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelVentana3Layout.createSequentialGroup()
                        .addComponent(txtCaracteristicas3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(JPanelVentana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelVentana3Layout.createSequentialGroup()
                    .addContainerGap(44, Short.MAX_VALUE)
                    .addComponent(txtImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );
        JPanelVentana3Layout.setVerticalGroup(
            JPanelVentana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelVentana3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(txtCaracteristicas3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSiguienteV3)
                .addGap(17, 17, 17))
            .addGroup(JPanelVentana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelVentana3Layout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(txtImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        bg.add(JPanelVentana3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 270, 220));

        txtImagen2.setText("Coche");

        btnSiguienteV2.setText("Siguiente");
        btnSiguienteV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteV2ActionPerformed(evt);
            }
        });

        txtCaracteristicas2.setText("jLabel1");

        javax.swing.GroupLayout JPanelVentana2Layout = new javax.swing.GroupLayout(JPanelVentana2);
        JPanelVentana2.setLayout(JPanelVentana2Layout);
        JPanelVentana2Layout.setHorizontalGroup(
            JPanelVentana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelVentana2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JPanelVentana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelVentana2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnSiguienteV2))
                    .addGroup(JPanelVentana2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(txtCaracteristicas2)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        JPanelVentana2Layout.setVerticalGroup(
            JPanelVentana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelVentana2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(JPanelVentana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelVentana2Layout.createSequentialGroup()
                        .addComponent(txtCaracteristicas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguienteV2)
                        .addGap(70, 70, 70))
                    .addGroup(JPanelVentana2Layout.createSequentialGroup()
                        .addComponent(txtImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))))
        );

        bg.add(JPanelVentana2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 310, 190));

        btnSeleccionar.setText("Seleccionar");

        txtCaracteristicas1.setText("Caracteristicas");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        txtImagen1.setText("Coche");

        javax.swing.GroupLayout JPanelVentana1Layout = new javax.swing.GroupLayout(JPanelVentana1);
        JPanelVentana1.setLayout(JPanelVentana1Layout);
        JPanelVentana1Layout.setHorizontalGroup(
            JPanelVentana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelVentana1Layout.createSequentialGroup()
                .addGroup(JPanelVentana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelVentana1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnSeleccionar))
                    .addComponent(txtCaracteristicas1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(JPanelVentana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelVentana1Layout.createSequentialGroup()
                        .addComponent(btnSiguiente)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelVentana1Layout.createSequentialGroup()
                        .addComponent(txtImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        JPanelVentana1Layout.setVerticalGroup(
            JPanelVentana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelVentana1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(txtCaracteristicas1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelVentana1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(txtImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnSiguiente)
                .addGap(69, 69, 69))
        );

        bg.add(JPanelVentana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 834, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        
        JPanelVentana1.setVisible(false);
        JPanelVentana2.setVisible(true); 
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnSiguienteV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteV2ActionPerformed
        // TODO add your handling code here:
        JPanelVentana2.setVisible(false);
        JPanelVentana3.setVisible(true); 
    }//GEN-LAST:event_btnSiguienteV2ActionPerformed

    private void btnSiguienteV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteV3ActionPerformed
        // TODO add your handling code here:
        JPanelVentana1.setVisible(true);
        JPanelVentana3.setVisible(false); 
    }//GEN-LAST:event_btnSiguienteV3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelVentana1;
    private javax.swing.JPanel JPanelVentana2;
    private javax.swing.JPanel JPanelVentana3;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnSiguienteV2;
    private javax.swing.JButton btnSiguienteV3;
    private javax.swing.JLabel txtCaracteristicas1;
    private javax.swing.JLabel txtCaracteristicas2;
    private javax.swing.JLabel txtCaracteristicas3;
    private javax.swing.JLabel txtImagen1;
    private javax.swing.JLabel txtImagen2;
    private javax.swing.JLabel txtImagen3;
    // End of variables declaration//GEN-END:variables
}
