/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package consecionario.Formularios;

import BD.ClienteDB;
import consecionario.Clases.Cliente;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author antoniosalinas
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    
    public void SetImageLabel(JLabel labelName, String resourcePath) {
    java.net.URL imgURL = getClass().getResource(resourcePath);
    if (imgURL == null) {
        System.err.println("No se encontró la imagen en: " + resourcePath);
        return;
    }

    // Esperar a que el JLabel tenga dimensiones válidas
    if (labelName.getWidth() == 0 || labelName.getHeight() == 0) {
        labelName.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ImageIcon imageIcon = new ImageIcon(imgURL);
                Image scaledImage = imageIcon.getImage().getScaledInstance(
                        labelName.getWidth(),
                        labelName.getHeight(),
                        Image.SCALE_SMOOTH
                );
                labelName.setIcon(new ImageIcon(scaledImage));
                labelName.removeComponentListener(this); // Para evitar múltiples llamadas
            }
        });
    } else {
        ImageIcon imageIcon = new ImageIcon(imgURL);
        Image scaledImage = imageIcon.getImage().getScaledInstance(
                labelName.getWidth(),
                labelName.getHeight(),
                Image.SCALE_SMOOTH
        );
        labelName.setIcon(new ImageIcon(scaledImage));
    }
}
    //inicializa el metodo para cargar la imagen deceada en el label decignado
    public void CargarImagen(){
     SetImageLabel(txtIconUsuario, "/consecionario/Imagenes/IconoGrupo.png");
    // SetImageLabel(txtIconVentas, "/consecionario/Imagenes/iconoVentasCarros.png");
    }
    public void cargarClientesEnTabla() {
    ClienteDB clienteDB = new ClienteDB();
    List<Cliente> listaClientes = clienteDB.obtenerTodosLosClientes();

    // Obtenemos el modelo de la tabla
    DefaultTableModel modelo = (DefaultTableModel) tblDatosClientes.getModel();
    modelo.setRowCount(0); // Limpiar tabla

    // Llenar la tabla con los datos
    for (Cliente cl : listaClientes) {
        Object[] fila = {
            cl.getNombre(),
            cl.getApellidoP(),
            cl.getApellidoM(),
            cl.getGenero(),
            cl.getTelefono(),
            cl.getCorreo()
        };
        modelo.addRow(fila);
    }
}
    public void PersonalizarTabla(){
        tblDatosClientes.setRowHeight(40); // Altura de cada fila
        tblDatosClientes.setGridColor(Color.decode("#00263A")); // Color de las líneas

// Cambiar fuente del contenido
tblDatosClientes.setFont(new Font("Segoe UI", Font.PLAIN, 14));

// Cambiar fondo y texto de la tabla
tblDatosClientes.setBackground(new Color(245, 245, 245));
tblDatosClientes.setForeground(Color.BLACK);

// Encabezados personalizados
JTableHeader header = tblDatosClientes.getTableHeader();
header.setFont(new Font("Segoe UI", Font.BOLD, 14));
header.setBackground(new Color(60, 63, 65));
header.setForeground(Color.WHITE);
    }
    private void mostrarTotalClientes() {
    ClienteDB db = new ClienteDB();
    int total = db.contarClientes();
    txtNumUsuarios.setText(String.valueOf(total));
}
    
    public Dashboard() {
        initComponents();
        CargarImagen();
        cargarClientesEnTabla();
        PersonalizarTabla();
        mostrarTotalClientes();
    }
    
    
    public void NumeroClientes(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        pnlNuevosUsuarios = new javax.swing.JPanel();
        txtNuevosClientes = new javax.swing.JLabel();
        txtIconUsuario = new javax.swing.JLabel();
        txtNumUsuarios = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        pnlContenidoNuevosClientes = new javax.swing.JPanel();
        txtInfoClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosClientes = new javax.swing.JTable();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        pnlNuevosUsuarios.setBackground(new java.awt.Color(255, 195, 0));
        pnlNuevosUsuarios.setPreferredSize(new java.awt.Dimension(352, 100));

        txtNuevosClientes.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtNuevosClientes.setForeground(new java.awt.Color(255, 255, 255));
        txtNuevosClientes.setText("Nuevos Clientes");

        txtIconUsuario.setText("jLabel3");

        txtNumUsuarios.setText("NumUsuarios");

        javax.swing.GroupLayout pnlNuevosUsuariosLayout = new javax.swing.GroupLayout(pnlNuevosUsuarios);
        pnlNuevosUsuarios.setLayout(pnlNuevosUsuariosLayout);
        pnlNuevosUsuariosLayout.setHorizontalGroup(
            pnlNuevosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevosUsuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlNuevosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNuevosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(txtIconUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlNuevosUsuariosLayout.setVerticalGroup(
            pnlNuevosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevosUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNuevosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIconUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlNuevosUsuariosLayout.createSequentialGroup()
                        .addComponent(txtNuevosClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        txtUbicacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        txtUbicacion.setText("Dashboard / Pagina Principal");

        txtInfoClientes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtInfoClientes.setForeground(new java.awt.Color(0, 0, 0));
        txtInfoClientes.setText("Información de clientes");

        tblDatosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellido Paterno", "Apellido Materno", "Genero", "Teléfonos", "Correo Electrónico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatosClientes);

        javax.swing.GroupLayout pnlContenidoNuevosClientesLayout = new javax.swing.GroupLayout(pnlContenidoNuevosClientes);
        pnlContenidoNuevosClientes.setLayout(pnlContenidoNuevosClientesLayout);
        pnlContenidoNuevosClientesLayout.setHorizontalGroup(
            pnlContenidoNuevosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoNuevosClientesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtInfoClientes)
                .addGap(566, 712, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlContenidoNuevosClientesLayout.setVerticalGroup(
            pnlContenidoNuevosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoNuevosClientesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtInfoClientes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenidoNuevosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenidoNuevosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlNuevosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUbicacion))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtUbicacion)
                .addGap(18, 18, 18)
                .addComponent(pnlNuevosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlContenidoNuevosClientes;
    private javax.swing.JPanel pnlNuevosUsuarios;
    private javax.swing.JTable tblDatosClientes;
    private javax.swing.JLabel txtIconUsuario;
    private javax.swing.JLabel txtInfoClientes;
    private javax.swing.JLabel txtNuevosClientes;
    private javax.swing.JLabel txtNumUsuarios;
    private javax.swing.JLabel txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
