/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package consecionario.Formularios;

import BD.CatalogoBD;
import consecionario.Clases.CardAuto;
import consecionario.Clases.CatalogoCarros;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;

/**
 *
 * @author antoniosalinas
 */
public class InventarioVisual extends javax.swing.JPanel {

    /**
     * Creates new form InventarioVisual
     */
    
      private CatalogoBD catalogoBD;

    // Constructor de InventarioVisual
    public InventarioVisual() {
        initComponents();
        catalogoBD = new CatalogoBD();  // Inicializamos el acceso a la base de datos
       
        cargarTodosLosAutos();  // Cargar todos los autos al inicio
        OrdenarCards();
    }

        private int numColumnas = 3;
    // Método para ordenar los cards
    public void OrdenarCards() {
        //pnlCards.setLayout(new FlowLayout(FlowLayout.LEFT, 40, 20));
         pnlCards.setLayout(new GridLayout(0, numColumnas, 30, 20));
    }

    // Método para agregar los panels con los autos
    public void AgregarPanels(List<CatalogoCarros> listaDeCarros) {
        pnlCards.removeAll();

        // Recorrer la lista y agregar los cards al panel
        for (CatalogoCarros carro : listaDeCarros) {
            
            CardAuto card = new CardAuto(
            carro.getImagen(),
        carro.getMarca(),
        carro.getModelo(),
        carro.getAnioFabricacion(),
        carro.getKilometraje(),
        carro.getPrecio()
    );
    pnlCards.add(card);
    
        
}


        // Actualizamos la interfaz
        pnlCards.revalidate();
        pnlCards.repaint();
    }

    // Cargar todos los autos inicialmente (sin filtro)
    public void cargarTodosLosAutos() {
        List<CatalogoCarros> listaDeCarros = catalogoBD.obtenerPorCategoria("Todos");  // "Todos" es un valor genérico que puede recuperar todos los autos
        AgregarPanels(listaDeCarros);  // Llamamos al método para agregar los autos al panel
    }

    // Método para filtrar autos por categoría
    public void filtrarPorCategoria(String categoria) {
        List<CatalogoCarros> listaDeCarros = catalogoBD.obtenerPorCategoria(categoria);
        AgregarPanels(listaDeCarros);  // Llamamos al método para agregar los autos filtrados al panel
    }

    // Método para agregar botones de filtro
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCards = new javax.swing.JPanel();

        jScrollPane1.setPreferredSize(new java.awt.Dimension(908, 510));

        javax.swing.GroupLayout pnlCardsLayout = new javax.swing.GroupLayout(pnlCards);
        pnlCards.setLayout(pnlCardsLayout);
        pnlCardsLayout.setHorizontalGroup(
            pnlCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        pnlCardsLayout.setVerticalGroup(
            pnlCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCards;
    // End of variables declaration//GEN-END:variables
}
