/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package consecionario.Formularios;

import BD.ClienteDB;
import BD.SegurosBD;
import consecionario.Cliente;
import consecionario.Seguro;
import javax.swing.JOptionPane;


/**
 *
 * @author antoniosalinas
 */
public class Seguros extends javax.swing.JPanel {
    private boolean clienteYaExiste = false;
    /**
     * Creates new form Seguros
     */
    public Seguros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelPersonalData = new javax.swing.JPanel();
        labelPersonalData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fieldNombre = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        fieldApellidoP = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        fieldApellidoM = new javax.swing.JTextField();
        labelApellidoM = new javax.swing.JLabel();
        fieldCurp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldLicencia = new javax.swing.JTextField();
        labelAge = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldTelefono = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        fieldCalle = new javax.swing.JTextField();
        fieldColonia = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        fieldMunicipio = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        fieldCiudad = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        fieldCP = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        fieldEstado = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fieldModelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldMarca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldAnio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fieldPlacas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldSerie = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fieldColor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboUso = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        fieldValorAuto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelCobertura = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        comboCobertura = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        checkVial = new javax.swing.JCheckBox();
        checkPerdidaTotal = new javax.swing.JCheckBox();
        checkLlantas = new javax.swing.JCheckBox();
        checkRobo = new javax.swing.JCheckBox();
        checkRCA = new javax.swing.JCheckBox();
        checkJuridico = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        comboPeriodo = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        comboPago = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        labelValorAsegurado = new javax.swing.JLabel();
        labelPrima = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(834, 840));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(810, 520));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("FORMULARIO SEGUROS");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        panelPersonalData.setBackground(new java.awt.Color(199, 0, 57));

        labelPersonalData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPersonalData.setForeground(new java.awt.Color(255, 255, 255));
        labelPersonalData.setText("DATOS PERSONALES");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DIRECCION");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(420, 150));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 150));

        fieldNombre.setPreferredSize(new java.awt.Dimension(80, 22));

        labelName.setText("Nombre(s)");

        fieldApellidoP.setPreferredSize(new java.awt.Dimension(80, 22));

        labelApellido.setText("Apellido P.");

        fieldApellidoM.setPreferredSize(new java.awt.Dimension(80, 22));

        labelApellidoM.setText("Apellido M.");

        fieldCurp.setPreferredSize(new java.awt.Dimension(130, 22));
        fieldCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurpActionPerformed(evt);
            }
        });

        jLabel2.setText("Curp");

        jLabel7.setText("Genero");

        fieldEdad.setPreferredSize(new java.awt.Dimension(70, 22));
        fieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEdadActionPerformed(evt);
            }
        });

        jLabel6.setText("Edad");

        fieldLicencia.setPreferredSize(new java.awt.Dimension(120, 22));
        fieldLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLicenciaActionPerformed(evt);
            }
        });

        labelAge.setText("No. Licencia");

        jLabel4.setText("Telefono");

        fieldTelefono.setPreferredSize(new java.awt.Dimension(150, 22));

        fieldEmail.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel5.setText("Correo Electronico");

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Sin especificar" }));
        comboGenero.setPreferredSize(new java.awt.Dimension(120, 22));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellidoM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(fieldCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelAge)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(labelApellido)
                    .addComponent(labelApellidoM)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(labelAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(715, 55));
        jPanel5.setMinimumSize(new java.awt.Dimension(715, 55));
        jPanel5.setPreferredSize(new java.awt.Dimension(715, 55));

        jLabel29.setText("Calle");

        fieldCalle.setPreferredSize(new java.awt.Dimension(100, 22));

        fieldColonia.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel33.setText("Colonia");

        fieldMunicipio.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel37.setText("Municipio");

        fieldCiudad.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel38.setText("Ciudad");

        fieldCP.setPreferredSize(new java.awt.Dimension(60, 22));
        fieldCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCPActionPerformed(evt);
            }
        });

        jLabel39.setText("CP");

        fieldEstado.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel30.setText("Estado");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(fieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(fieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(fieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel33)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel30)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(5, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATOS DEL VEHICULO");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(420, 155));
        jPanel6.setMinimumSize(new java.awt.Dimension(420, 155));
        jPanel6.setPreferredSize(new java.awt.Dimension(420, 155));

        jLabel9.setText("Modelo");

        fieldModelo.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel10.setText("Marca");

        fieldMarca.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel12.setText("Año");

        fieldAnio.setPreferredSize(new java.awt.Dimension(70, 22));

        jLabel14.setText("Placas");

        fieldPlacas.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel11.setText("No.de Serie");

        fieldSerie.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel16.setText("Color");

        fieldColor.setPreferredSize(new java.awt.Dimension(70, 22));

        jLabel13.setText("Tipo");

        jLabel15.setText("Uso del Auto");

        comboUso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Empresarial", "Uber/Didi" }));
        comboUso.setPreferredSize(new java.awt.Dimension(120, 22));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hatchback", "Sedan", "SUV" }));
        comboTipo.setPreferredSize(new java.awt.Dimension(120, 22));

        fieldValorAuto.setPreferredSize(new java.awt.Dimension(70, 22));

        jLabel20.setText("Precio Aprox.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(fieldPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(fieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(fieldValorAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addComponent(fieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldValorAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("COBERTURA");

        panelCobertura.setBackground(new java.awt.Color(255, 255, 255));
        panelCobertura.setMaximumSize(new java.awt.Dimension(280, 140));
        panelCobertura.setMinimumSize(new java.awt.Dimension(280, 140));
        panelCobertura.setPreferredSize(new java.awt.Dimension(280, 154));
        panelCobertura.setVerifyInputWhenFocusTarget(false);

        jLabel18.setText("Tipo de Cobertura");

        comboCobertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amplia", "Limitada", "Responsabilidad Civil" }));
        comboCobertura.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel19.setText("Coberturas Adicionales");

        checkVial.setText("Asistencia Vial");

        checkPerdidaTotal.setText("Perdida Total");

        checkLlantas.setText("Llantas y Cristales");

        checkRobo.setText("Robo de autopartes");

        checkRCA.setText("Civil Ampliada");

        checkJuridico.setText("Apoyo Juridico");

        javax.swing.GroupLayout panelCoberturaLayout = new javax.swing.GroupLayout(panelCobertura);
        panelCobertura.setLayout(panelCoberturaLayout);
        panelCoberturaLayout.setHorizontalGroup(
            panelCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(checkRobo)
                    .addGroup(panelCoberturaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkLlantas)
                    .addGroup(panelCoberturaLayout.createSequentialGroup()
                        .addGroup(panelCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkPerdidaTotal)
                            .addComponent(checkVial))
                        .addGap(25, 25, 25)
                        .addGroup(panelCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkRCA)
                            .addComponent(checkJuridico))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelCoberturaLayout.setVerticalGroup(
            panelCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(comboCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkVial)
                    .addComponent(checkRCA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPerdidaTotal)
                    .addComponent(checkJuridico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkRobo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkLlantas))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(280, 55));
        jPanel4.setMinimumSize(new java.awt.Dimension(280, 55));
        jPanel4.setPreferredSize(new java.awt.Dimension(280, 55));

        jLabel27.setText("Periodo");

        comboPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MENSUAL", "SEMESTRAL", "ANUAL" }));

        jLabel28.setText("Metodo de Pago");

        comboPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TARJETA", "TRANSFERENCIA", "EFECTIVO" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(comboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(comboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("PAGO Y COTIZACION");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(280, 150));
        jPanel3.setMinimumSize(new java.awt.Dimension(280, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 150));

        jLabel21.setText("Prima del seguro");

        jLabel23.setText("Valor Asegurado");

        labelValorAsegurado.setText("$ 0");

        labelPrima.setText("$ 0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPrima)
                    .addComponent(labelValorAsegurado))
                .addGap(62, 62, 62))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(labelValorAsegurado))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(labelPrima))
                .addGap(78, 78, 78)
                .addComponent(jLabel22))
        );

        btnContinuar.setBackground(new java.awt.Color(255, 153, 51));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPersonalDataLayout = new javax.swing.GroupLayout(panelPersonalData);
        panelPersonalData.setLayout(panelPersonalDataLayout);
        panelPersonalDataLayout.setHorizontalGroup(
            panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPersonalData)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(panelCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelPersonalDataLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(btnContinuar))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );
        panelPersonalDataLayout.setVerticalGroup(
            panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonalDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPersonalData)
                    .addComponent(jLabel17))
                .addGap(4, 4, 4)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(panelCobertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel26))
                .addGap(5, 5, 5)
                .addGroup(panelPersonalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPersonalDataLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnContinuar)))
                .addGap(20, 20, 20))
        );

        bg.add(panelPersonalData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 740, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void actualizarCalculos() {
    try {
        // Crear objeto seguro temporal
        Seguro seguro = new Seguro();
        
        // Obtener valores del formulario
        seguro.setValorBaseAuto(Integer.parseInt(fieldValorAuto.getText()));
        seguro.setEdadConductor(Integer.parseInt(fieldEdad.getText()));
        seguro.setCobertura(comboCobertura.getSelectedItem().toString());
        
        // Configurar coberturas adicionales
        seguro.setCoberturaVial(checkVial.isSelected());
        seguro.setCoberturaLlantas(checkLlantas.isSelected());
        // ... configurar otras coberturas
        
        // Calcular
        int prima = seguro.calcularPrima();
        int valorAsegurado = seguro.calcularValorAsegurado();
        
        // Actualizar labels
        labelPrima.setText(String.format("$%,d MXN", prima));
        labelValorAsegurado.setText(String.format("$%,d MXN", valorAsegurado));
        
    } catch (NumberFormatException e) {
        // Manejar campos vacíos o inválidos
        labelPrima.setText("$0 MXN");
        labelValorAsegurado.setText("$0 MXN");
    }
}
    
    public void setClienteYaExiste(boolean existe) {
        this.clienteYaExiste = existe;
    }
    
    public void setDatosCliente(Cliente cliente) {
    fieldNombre.setText(cliente.getNombre());
    fieldApellidoP.setText(cliente.getApellidoP());
    fieldApellidoM.setText(cliente.getApellidoM());
    fieldTelefono.setText(String.valueOf(cliente.getTelefono()));
    fieldEmail.setText(cliente.getCorreo());
    fieldCalle.setText(cliente.getCalle());
    fieldColonia.setText(cliente.getColonia());
    fieldMunicipio.setText(cliente.getMunicipio());
    fieldCiudad.setText(cliente.getCiudad());
    fieldEstado.setText(cliente.getEstado());
    fieldCP.setText(cliente.getCP());
    fieldCurp.setText(cliente.getCurp());
    fieldLicencia.setText(cliente.getLicencia());
    fieldEdad.setText(String.valueOf(cliente.getEdad()));
    
    // Configurar género
    setGenero(cliente.getGenero());
    //actualizarCalculos(); 
}

public void setGenero(String genero) {
    for (int i = 0; i < comboGenero.getItemCount(); i++) {
        if (comboGenero.getItemAt(i).equalsIgnoreCase(genero)) {
            comboGenero.setSelectedIndex(i);
            break;
        }
    }
}
    
    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        // --- Parte 1: Obtener datos del formulario ---
    Cliente cliente = new Cliente();
    cliente.setApellidoP(fieldApellidoP.getText());
    cliente.setApellidoM(fieldApellidoM.getText());
    cliente.setNombre(fieldNombre.getText());
    cliente.setTelefono(Long.parseLong(fieldTelefono.getText()));
    cliente.setCorreo(fieldEmail.getText());
    cliente.setCalle(fieldCalle.getText());
    cliente.setColonia(fieldColonia.getText());
    cliente.setMunicipio(fieldMunicipio.getText());
    cliente.setCiudad(fieldCiudad.getText());
    cliente.setEstado(fieldEstado.getText());
    cliente.setCP(fieldCP.getText());
    cliente.setCurp(fieldCurp.getText());
    cliente.setLicencia(fieldLicencia.getText());
    cliente.setGenero(comboGenero.getSelectedItem().toString());
    cliente.setEdad((int) Long.parseLong(fieldEdad.getText()));
    
    // --- Parte 2: Registrar cliente SOLO si no existe ---
    if (!clienteYaExiste) {
        ClienteDB dao = new ClienteDB();
        if (!dao.RegistrarClientes(cliente)) {
            JOptionPane.showMessageDialog(this, "Error al registrar cliente");
            return; // Detener el proceso si hay error
        }
    }
    
    // --- Parte 3: Procesar el seguro (siempre se ejecuta) ---
    Seguro seguro = new Seguro();
    seguro.setNombreS(fieldNombre.getText());
    seguro.setApellidoP(fieldApellidoP.getText());
    
    // Generar resumen del auto
    String resumenAuto = Seguro.generarResumenAuto(
        fieldMarca.getText(),
        fieldModelo.getText(), 
        fieldValorAuto.getText(),
        fieldPlacas.getText(),
        fieldColor.getText()
    );
    seguro.setAutoResumen(resumenAuto);
    
    // Configurar datos del seguro
    seguro.setCobertura(comboCobertura.getSelectedItem().toString());
    seguro.setPeriodo(comboPeriodo.getSelectedItem().toString());
    seguro.setMetodoP(comboPago.getSelectedItem().toString());
    seguro.setEdadConductor(cliente.getEdad());
    seguro.setGeneroConductor(cliente.getGenero());
    seguro.setValorBaseAuto(Integer.parseInt(fieldValorAuto.getText()));
    
    // Coberturas adicionales
    seguro.setCoberturaJuridico(checkJuridico.isSelected());
    seguro.setCoberturaLlantas(checkLlantas.isSelected());
    seguro.setCoberturaPerdidaTotal(checkPerdidaTotal.isSelected());
    seguro.setCoberturaRCA(checkRCA.isSelected());
    seguro.setCoberturaRobo(checkRobo.isSelected());
    seguro.setCoberturaVial(checkVial.isSelected());
    
    // Calcular y mostrar valores
    int valorAsegurado = seguro.calcularValorAsegurado();
    int prima = seguro.calcularPrima();
    labelPrima.setText(String.valueOf(prima) + " MXN");
    labelValorAsegurado.setText(String.valueOf(valorAsegurado) + " MXN");
    
    // Registrar seguro
    SegurosBD sao = new SegurosBD();
    if (sao.RegistrarSeguro(seguro)) {
        String mensaje = clienteYaExiste ? 
            "Seguro registrado para cliente existente" : 
            "Cliente nuevo y seguro registrados correctamente";
        JOptionPane.showMessageDialog(this, mensaje);
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar seguro");
    }

    }//GEN-LAST:event_btnContinuarActionPerformed

    private void fieldCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCPActionPerformed

    private void fieldLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLicenciaActionPerformed

    private void fieldCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurpActionPerformed

    private void fieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEdadActionPerformed

    
    
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JCheckBox checkJuridico;
    private javax.swing.JCheckBox checkLlantas;
    private javax.swing.JCheckBox checkPerdidaTotal;
    private javax.swing.JCheckBox checkRCA;
    private javax.swing.JCheckBox checkRobo;
    private javax.swing.JCheckBox checkVial;
    private javax.swing.JComboBox<String> comboCobertura;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JComboBox<String> comboPago;
    private javax.swing.JComboBox<String> comboPeriodo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboUso;
    private javax.swing.JTextField fieldAnio;
    private javax.swing.JTextField fieldApellidoM;
    private javax.swing.JTextField fieldApellidoP;
    private javax.swing.JTextField fieldCP;
    private javax.swing.JTextField fieldCalle;
    private javax.swing.JTextField fieldCiudad;
    private javax.swing.JTextField fieldColonia;
    private javax.swing.JTextField fieldColor;
    private javax.swing.JTextField fieldCurp;
    private javax.swing.JTextField fieldEdad;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEstado;
    private javax.swing.JTextField fieldLicencia;
    private javax.swing.JTextField fieldMarca;
    private javax.swing.JTextField fieldModelo;
    private javax.swing.JTextField fieldMunicipio;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldPlacas;
    private javax.swing.JTextField fieldSerie;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JTextField fieldValorAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelApellidoM;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPersonalData;
    private javax.swing.JLabel labelPrima;
    private javax.swing.JLabel labelValorAsegurado;
    private javax.swing.JPanel panelCobertura;
    private javax.swing.JPanel panelPersonalData;
    // End of variables declaration//GEN-END:variables
}
