/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package consecionario.Formularios;

import BD.ClienteDB;
import BD.ConexionBD;
import BD.SegurosBD;
import consecionario.Clases.CatalogoCarros;
import consecionario.Clases.Cliente;
import consecionario.Clases.GeneradorPDF;

import consecionario.Clases.PolizaSeguroPDF;
import consecionario.Clases.Seguro;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.time.LocalDate;
import java.util.concurrent.ExecutionException;


/**
 *
 * @author antoniosalinas
 */
public class Seguros extends javax.swing.JPanel {
    
    
     private void registrarHistorial(Cliente cliente, String tipoDocumento, String rutaArchivo) {
    Connection con = ConexionBD.conn();
    
    if (con != null) {
        try {
            String sql = "INSERT INTO historial_documentos (id_cliente, nombre_cliente, tipo_documento, ruta_archivo, fecha_registro) VALUES (?, ?, ?, ?, NOW())";
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, cliente.getId());
            ps.setString(2, cliente.getNombre() + " " + cliente.getApellidoP() + " " + cliente.getApellidoM());
            ps.setString(3, tipoDocumento);
            ps.setString(4, rutaArchivo);
            
            ps.executeUpdate();
            ps.close();
            con.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar historial: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos para registrar historial.");
    }
    }
     
    
    
    private boolean irACreditoDespues;
    private CatalogoCarros carro;
    private Seguro seguro;
    private Cliente cliente;
    
    private JPanel jPanelContenido;
     
     public Seguros(Cliente cliente, CatalogoCarros carro) {
        this.cliente = cliente;
        this.carro = carro;
        initComponents();
        inicializarListeners();
        configurarListeners();
        cargarDatosCliente(); 
        cargarDatosCarroSeleccionado();
       
    }
     
    public Seguros(Cliente cliente, CatalogoCarros carro, boolean irACreditoDespues) {
    initComponents();
    this.cliente = cliente;
    this.carro = carro;
    this.irACreditoDespues = irACreditoDespues;
    inicializarListeners();
        configurarListeners();
        cargarDatosCliente(); 
        cargarDatosCarroSeleccionado();

}
     
    private void cargarDatosCliente() {

    fieldNombre.setText(cliente.getNombre());
    fieldApellidoP.setText(cliente.getApellidoP());
    fieldApellidoM.setText(cliente.getApellidoM());
    fieldCurp.setText(cliente.getCurp());
    comboGenero.setSelectedItem(cliente.getGenero());
    fieldEdad.setText(String.valueOf(cliente.getEdad()));
    fieldTelefono.setText(String.valueOf(cliente.getTelefono()));
    fieldEmail.setText(cliente.getCorreo());

    fieldCalle.setText(cliente.getCalle());
    fieldColonia.setText(cliente.getColonia());
    fieldMunicipio.setText(cliente.getMunicipio());
    fieldEstado.setText(cliente.getEstado());
    fieldCP.setText(cliente.getCP());
    fieldLicencia.setText(cliente.getLicencia());
    
    
}
    private void cargarDatosCarroSeleccionado(){
    fieldModelo.setText(carro.getModelo());
    fieldMarca.setText(carro.getMarca());
    fieldAnio.setText(String.valueOf(carro.getAnioFabricacion()));
    fieldColor.setText(carro.getColor());
    comboTipo.setSelectedItem(carro.getCategoria());
    fieldValorAuto.setText(String.valueOf(carro.getPrecio()));
    fieldSerie.setText(String.valueOf(carro.getNoSerie()));
}
    public Seguros(JPanel jPanelContenido) {
        this.jPanelContenido = jPanelContenido;
        initComponents();
        inicializarListeners();
        configurarListeners();
    }
     
    
    public Seguros() {
        initComponents();
        inicializarListeners();
        configurarListeners();
    }
     
    private boolean clienteYaExiste = false;
    private DocumentListener documentListener;
    private ItemListener checkboxListener;
    private java.awt.event.ActionListener comboBoxListener;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();
        bgDatosCliente = new javax.swing.JPanel();
        lblDatosCliente = new javax.swing.JLabel();
        pnlDatosCliente = new javax.swing.JPanel();
        fieldApellidoP = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        fieldApellidoM = new javax.swing.JTextField();
        labelApellidoM = new javax.swing.JLabel();
        fieldCurp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldLicencia = new javax.swing.JTextField();
        labelAge = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldTelefono = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        fieldNombre = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        bgDatosVehiculo = new javax.swing.JPanel();
        lblDatosVehiculo = new javax.swing.JLabel();
        pnlDatosVehiculo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fieldModelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldMarca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldAnio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fieldPlacas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldSerie = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fieldColor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboUso = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        fieldValorAuto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        bgDireccionCliente = new javax.swing.JPanel();
        lblDireccion = new javax.swing.JLabel();
        pnlDireccionCliente = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        fieldCalle = new javax.swing.JTextField();
        fieldColonia = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        fieldMunicipio = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        fieldCP = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        fieldEstado = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        bgCobertura = new javax.swing.JPanel();
        lblCobertura = new javax.swing.JLabel();
        pnlCobertura = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        comboCobertura = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        checkVial = new javax.swing.JCheckBox();
        checkPerdidaTotal = new javax.swing.JCheckBox();
        checkLlantas = new javax.swing.JCheckBox();
        checkRobo = new javax.swing.JCheckBox();
        checkRCA = new javax.swing.JCheckBox();
        checkJuridico = new javax.swing.JCheckBox();
        bgPago_Cotizacion = new javax.swing.JPanel();
        lblPagoCotizacion = new javax.swing.JLabel();
        pnlPago = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        comboPeriodo = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        comboPago = new javax.swing.JComboBox<>();
        pnlCotizacion = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        labelValorAsegurado = new javax.swing.JLabel();
        labelPrima = new javax.swing.JLabel();
        bgBtnContinuar = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(834, 840));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(810, 520));
        bg.setLayout(new java.awt.BorderLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitle.setText("Formulario Seguros");
        lblTitle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        bg.add(lblTitle, java.awt.BorderLayout.NORTH);

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenido.setPreferredSize(new java.awt.Dimension(1127, 571));

        bgDatosCliente.setBackground(new java.awt.Color(0, 38, 58));

        lblDatosCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDatosCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblDatosCliente.setText("DATOS PERSONALES");

        pnlDatosCliente.setBackground(new java.awt.Color(245, 245, 245));
        pnlDatosCliente.setMaximumSize(new java.awt.Dimension(420, 150));
        pnlDatosCliente.setMinimumSize(new java.awt.Dimension(420, 150));
        pnlDatosCliente.setPreferredSize(new java.awt.Dimension(420, 150));

        fieldApellidoP.setPreferredSize(new java.awt.Dimension(80, 22));

        labelApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelApellido.setText("Apellido P.");

        fieldApellidoM.setPreferredSize(new java.awt.Dimension(80, 22));

        labelApellidoM.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelApellidoM.setText("Apellido M.");

        fieldCurp.setPreferredSize(new java.awt.Dimension(130, 22));
        fieldCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurpActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Curp");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("Genero");

        fieldEdad.setPreferredSize(new java.awt.Dimension(70, 22));
        fieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEdadActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Edad");

        fieldLicencia.setPreferredSize(new java.awt.Dimension(120, 22));
        fieldLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLicenciaActionPerformed(evt);
            }
        });

        labelAge.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelAge.setText("No. Licencia");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Telefono");

        fieldTelefono.setPreferredSize(new java.awt.Dimension(150, 22));

        fieldEmail.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("Correo Electronico");

        comboGenero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Sin especificar" }));
        comboGenero.setPreferredSize(new java.awt.Dimension(120, 22));
        comboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGeneroActionPerformed(evt);
            }
        });

        fieldNombre.setPreferredSize(new java.awt.Dimension(80, 22));

        labelName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelName.setText("Nombre(s)");

        javax.swing.GroupLayout pnlDatosClienteLayout = new javax.swing.GroupLayout(pnlDatosCliente);
        pnlDatosCliente.setLayout(pnlDatosClienteLayout);
        pnlDatosClienteLayout.setHorizontalGroup(
            pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                        .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldApellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelApellido))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldApellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelApellidoM))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(fieldCurp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                        .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(comboGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldLicencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelAge)))
                            .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(fieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(122, 122, 122))))
        );
        pnlDatosClienteLayout.setVerticalGroup(
            pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido)
                    .addComponent(labelApellidoM)
                    .addComponent(jLabel2)
                    .addComponent(labelName))
                .addGap(1, 1, 1)
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(labelAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgDatosClienteLayout = new javax.swing.GroupLayout(bgDatosCliente);
        bgDatosCliente.setLayout(bgDatosClienteLayout);
        bgDatosClienteLayout.setHorizontalGroup(
            bgDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgDatosClienteLayout.createSequentialGroup()
                        .addComponent(lblDatosCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                .addContainerGap())
        );
        bgDatosClienteLayout.setVerticalGroup(
            bgDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        bgDatosVehiculo.setBackground(new java.awt.Color(0, 38, 58));

        lblDatosVehiculo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblDatosVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblDatosVehiculo.setText("DATOS DEL VEHICULO");

        pnlDatosVehiculo.setBackground(new java.awt.Color(245, 245, 245));
        pnlDatosVehiculo.setMaximumSize(new java.awt.Dimension(420, 155));
        pnlDatosVehiculo.setMinimumSize(new java.awt.Dimension(420, 155));
        pnlDatosVehiculo.setPreferredSize(new java.awt.Dimension(420, 155));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("Modelo");

        fieldModelo.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setText("Marca");

        fieldMarca.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setText("Año");

        fieldAnio.setPreferredSize(new java.awt.Dimension(90, 22));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setText("Placas");

        fieldPlacas.setPreferredSize(new java.awt.Dimension(150, 22));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("No.de Serie");

        fieldSerie.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel16.setText("Color");

        fieldColor.setPreferredSize(new java.awt.Dimension(90, 22));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setText("Tipo");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setText("Uso del Auto");

        comboUso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboUso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Empresarial", "Uber/Didi" }));
        comboUso.setPreferredSize(new java.awt.Dimension(150, 22));

        comboTipo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hatchback", "Sedan", "SUV" }));
        comboTipo.setPreferredSize(new java.awt.Dimension(120, 22));

        fieldValorAuto.setPreferredSize(new java.awt.Dimension(90, 22));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel20.setText("Precio Aprox.");

        javax.swing.GroupLayout pnlDatosVehiculoLayout = new javax.swing.GroupLayout(pnlDatosVehiculo);
        pnlDatosVehiculo.setLayout(pnlDatosVehiculoLayout);
        pnlDatosVehiculoLayout.setHorizontalGroup(
            pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)
                                    .addComponent(fieldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(fieldMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12)))
                                    .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16))))
                            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                .addComponent(fieldPlacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(63, 63, 63))
                    .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                        .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                .addComponent(comboUso, 0, 221, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(114, 114, 114)))
                        .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                .addComponent(comboTipo, 0, 229, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(167, 167, 167)))
                        .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                                .addComponent(fieldValorAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addGap(74, 74, 74))))))
        );
        pnlDatosVehiculoLayout.setVerticalGroup(
            pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosVehiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(5, 5, 5)
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldValorAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout bgDatosVehiculoLayout = new javax.swing.GroupLayout(bgDatosVehiculo);
        bgDatosVehiculo.setLayout(bgDatosVehiculoLayout);
        bgDatosVehiculoLayout.setHorizontalGroup(
            bgDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDatosVehiculoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnlDatosVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bgDatosVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgDatosVehiculoLayout.setVerticalGroup(
            bgDatosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgDatosVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosVehiculo)
                .addGap(4, 4, 4)
                .addComponent(pnlDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bgDireccionCliente.setBackground(new java.awt.Color(0, 38, 58));

        lblDireccion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("DIRECCION");

        pnlDireccionCliente.setBackground(new java.awt.Color(245, 245, 245));
        pnlDireccionCliente.setMaximumSize(new java.awt.Dimension(715, 55));
        pnlDireccionCliente.setMinimumSize(new java.awt.Dimension(715, 55));
        pnlDireccionCliente.setPreferredSize(new java.awt.Dimension(715, 55));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel29.setText("Calle");

        fieldCalle.setPreferredSize(new java.awt.Dimension(160, 22));

        fieldColonia.setPreferredSize(new java.awt.Dimension(130, 22));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel33.setText("Colonia");

        fieldMunicipio.setPreferredSize(new java.awt.Dimension(130, 22));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel37.setText("Municipio");

        fieldCP.setPreferredSize(new java.awt.Dimension(60, 22));
        fieldCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCPActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel39.setText("CP");

        fieldEstado.setPreferredSize(new java.awt.Dimension(130, 22));

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel30.setText("Ciudad / Estado");

        javax.swing.GroupLayout pnlDireccionClienteLayout = new javax.swing.GroupLayout(pnlDireccionCliente);
        pnlDireccionCliente.setLayout(pnlDireccionClienteLayout);
        pnlDireccionClienteLayout.setHorizontalGroup(
            pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDireccionClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCalle, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jLabel29))
                .addGap(20, 20, 20)
                .addGroup(pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(fieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldCP, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addGroup(pnlDireccionClienteLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDireccionClienteLayout.setVerticalGroup(
            pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDireccionClienteLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel33)
                    .addComponent(jLabel37)
                    .addComponent(jLabel30)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgDireccionClienteLayout = new javax.swing.GroupLayout(bgDireccionCliente);
        bgDireccionCliente.setLayout(bgDireccionClienteLayout);
        bgDireccionClienteLayout.setHorizontalGroup(
            bgDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDireccionClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgDireccionClienteLayout.createSequentialGroup()
                        .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bgDireccionClienteLayout.setVerticalGroup(
            bgDireccionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDireccionClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        bgCobertura.setBackground(new java.awt.Color(0, 38, 58));

        lblCobertura.setBackground(new java.awt.Color(51, 51, 255));
        lblCobertura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCobertura.setForeground(new java.awt.Color(255, 255, 255));
        lblCobertura.setText("COBERTURA");

        pnlCobertura.setBackground(new java.awt.Color(245, 245, 245));
        pnlCobertura.setMaximumSize(new java.awt.Dimension(280, 140));
        pnlCobertura.setMinimumSize(new java.awt.Dimension(280, 140));
        pnlCobertura.setPreferredSize(new java.awt.Dimension(280, 154));
        pnlCobertura.setVerifyInputWhenFocusTarget(false);

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel18.setText("Tipo de Cobertura");

        comboCobertura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboCobertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amplia", "Limitada", "Responsabilidad Civil" }));
        comboCobertura.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel19.setText("Coberturas Adicionales");

        checkVial.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkVial.setText("Asistencia Vial");

        checkPerdidaTotal.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkPerdidaTotal.setText("Perdida Total");

        checkLlantas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkLlantas.setText("Llantas y Cristales");

        checkRobo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkRobo.setText("Robo de autopartes");

        checkRCA.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkRCA.setText("Civil Ampliada");

        checkJuridico.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkJuridico.setText("Apoyo Juridico");

        javax.swing.GroupLayout pnlCoberturaLayout = new javax.swing.GroupLayout(pnlCobertura);
        pnlCobertura.setLayout(pnlCoberturaLayout);
        pnlCoberturaLayout.setHorizontalGroup(
            pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCoberturaLayout.createSequentialGroup()
                        .addComponent(checkRobo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(checkLlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel19)
                    .addGroup(pnlCoberturaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCoberturaLayout.createSequentialGroup()
                        .addGroup(pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCoberturaLayout.createSequentialGroup()
                                .addComponent(checkPerdidaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(checkVial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlCoberturaLayout.createSequentialGroup()
                                .addComponent(checkRCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))
                        .addGap(14, 14, 14)))
                .addGap(25, 25, 25))
        );
        pnlCoberturaLayout.setVerticalGroup(
            pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkVial)
                    .addComponent(checkRCA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPerdidaTotal)
                    .addComponent(checkJuridico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRobo)
                    .addComponent(checkLlantas))
                .addContainerGap())
        );

        javax.swing.GroupLayout bgCoberturaLayout = new javax.swing.GroupLayout(bgCobertura);
        bgCobertura.setLayout(bgCoberturaLayout);
        bgCoberturaLayout.setHorizontalGroup(
            bgCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgCoberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgCoberturaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblCobertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bgCoberturaLayout.setVerticalGroup(
            bgCoberturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgCoberturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCobertura, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCobertura, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        bgPago_Cotizacion.setBackground(new java.awt.Color(0, 38, 58));

        lblPagoCotizacion.setBackground(new java.awt.Color(51, 51, 255));
        lblPagoCotizacion.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblPagoCotizacion.setForeground(new java.awt.Color(255, 255, 255));
        lblPagoCotizacion.setText("PAGO Y COTIZACION");

        pnlPago.setBackground(new java.awt.Color(245, 245, 245));
        pnlPago.setMaximumSize(new java.awt.Dimension(280, 55));
        pnlPago.setMinimumSize(new java.awt.Dimension(280, 55));
        pnlPago.setPreferredSize(new java.awt.Dimension(280, 55));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel27.setText("Periodo");

        comboPeriodo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MENSUAL", "SEMESTRAL", "ANUAL" }));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel28.setText("Metodo de Pago");

        comboPago.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        comboPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TARJETA", "TRANSFERENCIA", "EFECTIVO" }));

        javax.swing.GroupLayout pnlPagoLayout = new javax.swing.GroupLayout(pnlPago);
        pnlPago.setLayout(pnlPagoLayout);
        pnlPagoLayout.setHorizontalGroup(
            pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(comboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(comboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        pnlPagoLayout.setVerticalGroup(
            pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlCotizacion.setBackground(new java.awt.Color(245, 245, 245));
        pnlCotizacion.setMaximumSize(new java.awt.Dimension(280, 150));
        pnlCotizacion.setMinimumSize(new java.awt.Dimension(280, 150));
        pnlCotizacion.setPreferredSize(new java.awt.Dimension(280, 150));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel21.setText("Prima del seguro");

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel23.setText("Valor Asegurado");

        labelValorAsegurado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelValorAsegurado.setText("$ 0");

        labelPrima.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelPrima.setText("$ 0");

        javax.swing.GroupLayout pnlCotizacionLayout = new javax.swing.GroupLayout(pnlCotizacion);
        pnlCotizacion.setLayout(pnlCotizacionLayout);
        pnlCotizacionLayout.setHorizontalGroup(
            pnlCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCotizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValorAsegurado)
                    .addComponent(labelPrima))
                .addGap(62, 62, 62))
        );
        pnlCotizacionLayout.setVerticalGroup(
            pnlCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCotizacionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorAsegurado)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(pnlCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPrima)
                    .addComponent(jLabel21))
                .addGap(51, 51, 51)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgPago_CotizacionLayout = new javax.swing.GroupLayout(bgPago_Cotizacion);
        bgPago_Cotizacion.setLayout(bgPago_CotizacionLayout);
        bgPago_CotizacionLayout.setHorizontalGroup(
            bgPago_CotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPago_CotizacionLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(bgPago_CotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCotizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addGroup(bgPago_CotizacionLayout.createSequentialGroup()
                        .addComponent(lblPagoCotizacion)
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addComponent(pnlPago, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addContainerGap())
        );
        bgPago_CotizacionLayout.setVerticalGroup(
            bgPago_CotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPago_CotizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPagoCotizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPago, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        bgBtnContinuar.setBackground(new java.awt.Color(255, 255, 255));

        btnContinuar.setBackground(new java.awt.Color(255, 153, 51));
        btnContinuar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setPreferredSize(new java.awt.Dimension(150, 23));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgBtnContinuarLayout = new javax.swing.GroupLayout(bgBtnContinuar);
        bgBtnContinuar.setLayout(bgBtnContinuarLayout);
        bgBtnContinuarLayout.setHorizontalGroup(
            bgBtnContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBtnContinuarLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(249, 249, 249))
        );
        bgBtnContinuarLayout.setVerticalGroup(
            bgBtnContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBtnContinuarLayout.createSequentialGroup()
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bgDatosVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bgDireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bgDatosCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bgCobertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bgPago_Cotizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(bgBtnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bgDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(bgDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bgDatosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(bgPago_Cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bgCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bgBtnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(516, 516, 516))
        );

        bg.add(pnlContenido, java.awt.BorderLayout.CENTER);
        pnlContenido.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void inicializarListeners() {
        documentListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizarCalculos();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizarCalculos();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizarCalculos();
            }
        };
        
        checkboxListener = new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                actualizarCalculos();
            }
        };
        
        comboBoxListener = new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                actualizarCalculos();
            }
        };
    }
    
    // Método para asignar los listeners a los componentes
    private void configurarListeners() {
        // Campos de texto
        fieldValorAuto.getDocument().addDocumentListener(documentListener);
        fieldEdad.getDocument().addDocumentListener(documentListener);
        
        // Comboboxes
        comboCobertura.addActionListener(comboBoxListener);
        comboPeriodo.addActionListener(comboBoxListener);
        comboGenero.addActionListener(comboBoxListener);
        
        // Checkboxes
        checkVial.addItemListener(checkboxListener);
        checkPerdidaTotal.addItemListener(checkboxListener);
        checkLlantas.addItemListener(checkboxListener);
        checkRobo.addItemListener(checkboxListener);
        checkRCA.addItemListener(checkboxListener);
        checkJuridico.addItemListener(checkboxListener);
    }
    
    private void actualizarCalculos() {
        System.out.println("Método actualizarCalculos() ejecutado");
    try {
        if (fieldValorAuto.getText().trim().isEmpty()) {
            labelPrima.setText("$0.00 MXN");
            labelValorAsegurado.setText("$0.00 MXN");
            return;
        }
         double valorAuto = Double.parseDouble(fieldValorAuto.getText());
        if (valorAuto <= 0) {
            throw new NumberFormatException("El valor debe ser positivo");
        }
        
        

        Seguro seguro = new Seguro();
        seguro.setValorBaseAuto(valorAuto);
        //seguro.setValorBaseAuto(Double.parseDouble(fieldValorAuto.getText()));
        seguro.setEdadConductor(fieldEdad.getText().trim().isEmpty() ? 30 : Integer.parseInt(fieldEdad.getText()));
        seguro.setGeneroConductor(comboGenero.getSelectedItem().toString());
        seguro.setCobertura(comboCobertura.getSelectedItem().toString());
        seguro.setPeriodo(comboPeriodo.getSelectedItem().toString());
        seguro.setCoberturaVial(checkVial.isSelected());
        seguro.setCoberturaLlantas(checkLlantas.isSelected());
        seguro.setCoberturaPerdidaTotal(checkPerdidaTotal.isSelected());
        seguro.setCoberturaRCA(checkRCA.isSelected());
        seguro.setCoberturaRobo(checkRobo.isSelected());
        seguro.setCoberturaJuridico(checkJuridico.isSelected());
        seguro.setNoSerie(fieldSerie.getText());
        
        double valorAsegurado = seguro.calcularValorAsegurado();
        double prima = seguro.calcularPrima();
        
        System.out.println("[DEBUG] Valor base del auto: " + seguro.getValorBaseAuto());
        System.out.println("[DEBUG] Cobertura seleccionada: " + seguro.getCobertura());
        System.out.println("[DEBUG] Valor asegurado calculado: " + valorAsegurado);
        System.out.println("[DEBUG] Prima calculada: " + prima);
        
        labelPrima.setText(String.format("$%,.2f MXN", prima));
        labelValorAsegurado.setText(String.format("$%,.2f MXN", valorAsegurado));
        
    } catch (NumberFormatException e) {
        labelPrima.setText("$0.00 MXN");
        labelValorAsegurado.setText("$0.00 MXN");
    }
}
    
    public void setClienteYaExiste(boolean existe) {
        this.clienteYaExiste = existe;
    }
    
    public void setDatosCliente(Cliente cliente) {
    fieldNombre.setText(cliente.getNombre());
    fieldApellidoP.setText(cliente.getApellidoP());
    fieldApellidoM.setText(cliente.getApellidoM());
    fieldTelefono.setText(String.valueOf(cliente.getTelefono()));
    fieldEmail.setText(cliente.getCorreo());
    fieldCalle.setText(cliente.getCalle());
    fieldColonia.setText(cliente.getColonia());
    fieldMunicipio.setText(cliente.getMunicipio());
    
    fieldEstado.setText(cliente.getEstado());
    fieldCP.setText(cliente.getCP());
    fieldCurp.setText(cliente.getCurp());
    fieldLicencia.setText(cliente.getLicencia());
    fieldEdad.setText(String.valueOf(cliente.getEdad()));
    
    // Configurar género
    setGenero(cliente.getGenero());
    //actualizarCalculos(); 
}

    public void setGenero(String genero) {
    for (int i = 0; i < comboGenero.getItemCount(); i++) {
        if (comboGenero.getItemAt(i).equalsIgnoreCase(genero)) {
            comboGenero.setSelectedIndex(i);
            break;
        }
    }
}
    
    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        // --- Parte 1: Obtener datos del formulario ---
        Cliente cliente = new Cliente();
        cliente.setApellidoP(fieldApellidoP.getText());
        cliente.setApellidoM(fieldApellidoM.getText());
        cliente.setNombre(fieldNombre.getText());
        cliente.setTelefono(Long.parseLong(fieldTelefono.getText()));
        cliente.setCorreo(fieldEmail.getText());
        cliente.setCalle(fieldCalle.getText());
        cliente.setColonia(fieldColonia.getText());
        cliente.setMunicipio(fieldMunicipio.getText());
        cliente.setEstado(fieldEstado.getText());
        cliente.setCP(fieldCP.getText());
        cliente.setCurp(fieldCurp.getText());
        cliente.setLicencia(fieldLicencia.getText());
        cliente.setGenero(comboGenero.getSelectedItem().toString());
        cliente.setEdad((int) Long.parseLong(fieldEdad.getText()));

        // 2. Validar campos obligatorios
        if (fieldValorAuto.getText().trim().isEmpty() || fieldNombre.getText().trim().isEmpty() || 
            fieldApellidoP.getText().trim().isEmpty() || fieldTelefono.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Configurar diálogo de carga
        JDialog loadingDialog = new JDialog();
        loadingDialog.setUndecorated(true);
        loadingDialog.setSize(250, 100);
        loadingDialog.setLocationRelativeTo(this);
    
        //JPanel panel = new JPanel(new BorderLayout());
        //panel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
    
        //JProgressBar progressBar = new JProgressBar();
        //progressBar.setIndeterminate(true);
        //JLabel label = new JLabel("Procesando pago...", JLabel.CENTER);
    
        //panel.add(progressBar, BorderLayout.CENTER);
        //panel.add(label, BorderLayout.SOUTH);
        //loadingDialog.add(panel);
        //loadingDialog.setVisible(true);

        // 4. Ejecutar en segundo plano (CON TIEMPO EXTENDIDO)
        new Thread(() -> {
            try {
            
            //Thread.sleep(3000); // Espera inicial de 3 segundos (simula procesamiento)
            
            Cliente clientes = new Cliente();
            clientes.setNombre(fieldNombre.getText());
            clientes.setApellidoP(fieldApellidoP.getText());
            clientes.setApellidoM(fieldApellidoM.getText());
            clientes.setTelefono(Long.parseLong(fieldTelefono.getText()));
            clientes.setCorreo(fieldEmail.getText());
            clientes.setCalle(fieldCalle.getText());
            clientes.setColonia(fieldColonia.getText());
            clientes.setMunicipio(fieldMunicipio.getText());
            
            clientes.setEstado(fieldEstado.getText());
            clientes.setCP(fieldCP.getText());
            clientes.setCurp(fieldCurp.getText());
            clientes.setLicencia(fieldLicencia.getText());
            clientes.setGenero(comboGenero.getSelectedItem().toString());
            clientes.setEdad(Integer.parseInt(fieldEdad.getText()));

            if (!clienteYaExiste) {
                ClienteDB clienteDB = new ClienteDB();
                if (!clienteDB.RegistrarClientes(clientes)) {
                    throw new Exception("Error al registrar cliente");
                }
            }
            
            
            Seguro seguro = new Seguro();
            seguro.setNombreS(fieldNombre.getText());
            seguro.setApellidoP(fieldApellidoP.getText());
            seguro.setNoSerie(fieldSerie.getText());
            seguro.setPlacas(fieldPlacas.getText());
            seguro.setAutoResumen(Seguro.generarResumenAuto(
                fieldMarca.getText(),
                fieldModelo.getText(),
                fieldAnio.getText(),
                fieldPlacas.getText(),
                fieldColor.getText()
            ));
            seguro.setCobertura(comboCobertura.getSelectedItem().toString());
            seguro.setPeriodo(comboPeriodo.getSelectedItem().toString());
            seguro.setMetodoP(comboPago.getSelectedItem().toString());
            seguro.setValor(Double.parseDouble(labelValorAsegurado.getText().replaceAll("[^0-9.]", "")));
            seguro.setPrima(Double.parseDouble(labelPrima.getText().replaceAll("[^0-9.]", "")));
            seguro.setEdadConductor(clientes.getEdad());
            seguro.setGeneroConductor(clientes.getGenero());
            seguro.setValorBaseAuto(Double.parseDouble(fieldValorAuto.getText()));
            seguro.setCoberturaJuridico(checkJuridico.isSelected());
            seguro.setCoberturaLlantas(checkLlantas.isSelected());
            seguro.setCoberturaPerdidaTotal(checkPerdidaTotal.isSelected());
            seguro.setCoberturaRCA(checkRCA.isSelected());
            seguro.setCoberturaRobo(checkRobo.isSelected());
            seguro.setCoberturaVial(checkVial.isSelected());

            SegurosBD segurosBD = new SegurosBD();
            boolean resultado = segurosBD.RegistrarSeguro(seguro);

       
           
             SwingUtilities.invokeLater(() -> {
                loadingDialog.dispose();
                if (resultado) {
                    JOptionPane.showMessageDialog(Seguros.this, 
                        "✅ Pago aprobado", 
                        "Éxito", 
                        JOptionPane.INFORMATION_MESSAGE);
                    
                    try {
                        
                         // 1. Generar PDF Venta
GeneradorPDF.generarResumenVenta(cliente, carro, null);

// 2. Armar manualmente la ruta
String rutaVenta = "src/consecionario/Facturas/Ventas/Resumen_Venta_" + cliente.getNombre().replaceAll("\\s+", "_") + ".pdf";
String rutaSeguro = "src/consecionario/Facturas/PolizaSeguro/Poliza_Seguro_" + cliente.getNombre().replaceAll("\\s+", "_") + ".pdf";
// 3. Registrar historial
registrarHistorial(cliente, "Venta", rutaVenta);
    
                        
                        
        // Generar PDF del seguro
        PolizaSeguroPDF.generarResumenSeguro(cliente, carro, seguro, null);

        

        // Registrar historial
       registrarHistorial(cliente, "Seguro", rutaSeguro);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(Seguros.this, 
            "Error al generar el PDF del seguro: " + ex.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
  
                    // Aquí comprobamos si el cliente eligió "Ambos" y si es así, vamos a créditos
                    if (irACreditoDespues) {
                        // Mostrar el formulario de Créditos
                        Principal ventanaPrincipal = (Principal) javax.swing.SwingUtilities.getWindowAncestor(Seguros.this);
                        
                        // Cambiar al panel de créditos
                        Creditos creditosPanel = new Creditos(cliente, carro);  // Usar datos correctos
                        ventanaPrincipal.setPanelContenido(creditosPanel);
                    }
                } else {
                    JOptionPane.showMessageDialog(Seguros.this, 
                        "Error en el proceso", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
            });
            
        } catch (Exception e) {
            SwingUtilities.invokeLater(() -> {
                loadingDialog.dispose();
                JOptionPane.showMessageDialog(Seguros.this, 
                    "Error: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            });
        }
    }).start();
        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void fieldCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCPActionPerformed

    private void fieldLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLicenciaActionPerformed

    private void fieldCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurpActionPerformed

    private void fieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEdadActionPerformed

    private void comboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGeneroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgBtnContinuar;
    private javax.swing.JPanel bgCobertura;
    private javax.swing.JPanel bgDatosCliente;
    private javax.swing.JPanel bgDatosVehiculo;
    private javax.swing.JPanel bgDireccionCliente;
    private javax.swing.JPanel bgPago_Cotizacion;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JCheckBox checkJuridico;
    private javax.swing.JCheckBox checkLlantas;
    private javax.swing.JCheckBox checkPerdidaTotal;
    private javax.swing.JCheckBox checkRCA;
    private javax.swing.JCheckBox checkRobo;
    private javax.swing.JCheckBox checkVial;
    private javax.swing.JComboBox<String> comboCobertura;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JComboBox<String> comboPago;
    private javax.swing.JComboBox<String> comboPeriodo;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboUso;
    private javax.swing.JTextField fieldAnio;
    private javax.swing.JTextField fieldApellidoM;
    private javax.swing.JTextField fieldApellidoP;
    private javax.swing.JTextField fieldCP;
    private javax.swing.JTextField fieldCalle;
    private javax.swing.JTextField fieldColonia;
    private javax.swing.JTextField fieldColor;
    private javax.swing.JTextField fieldCurp;
    private javax.swing.JTextField fieldEdad;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEstado;
    private javax.swing.JTextField fieldLicencia;
    private javax.swing.JTextField fieldMarca;
    private javax.swing.JTextField fieldModelo;
    private javax.swing.JTextField fieldMunicipio;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldPlacas;
    private javax.swing.JTextField fieldSerie;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JTextField fieldValorAuto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelApellidoM;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPrima;
    private javax.swing.JLabel labelValorAsegurado;
    private javax.swing.JLabel lblCobertura;
    private javax.swing.JLabel lblDatosCliente;
    private javax.swing.JLabel lblDatosVehiculo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblPagoCotizacion;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCobertura;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlCotizacion;
    private javax.swing.JPanel pnlDatosCliente;
    private javax.swing.JPanel pnlDatosVehiculo;
    private javax.swing.JPanel pnlDireccionCliente;
    private javax.swing.JPanel pnlPago;
    // End of variables declaration//GEN-END:variables
}
