/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package consecionario.Formularios;


import BD.ClienteDB;

import consecionario.Cliente;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author antoniosalinas
 */




public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    
   

    String placeholderApellidoP = "Apellido Paterno";
    String placeholderApellidoM ="Apellido Materno";
    String placeholderNombre ="Nombre (s)";
    String placeholderTelefono ="Teléfono Celular";
    String placeholderCorreo ="Correo Electrónico";
    String placeholderCalle ="Calle";
    String placeholderColonia ="Colonia";
    String placeholderMunicipio ="Población, Alcaldía o Municipio";
    String placeholderCiudad ="Ciudad";
    String placeholderEstado ="Estado";
    String placeholderCP ="Código Postal";
    String placeholderMarca ="Marca";
    String placeholderModelo ="Modelo";
    String placeholderTipo ="Tipo";
    String placeholderColorCarro ="Color";
    String placeholderAnio ="Año";
    String placeholderEstados ="Condición";
    
    Color placeholderColor= Color.GRAY;
    Color normalColor = Color.BLACK;
    
    public Ventas() {
        initComponents();
        
        
        
        
        txtApellidoP.setText(placeholderApellidoP);
        txtApellidoP.setForeground(placeholderColor);
        
        txtApellidoM.setText(placeholderApellidoM);
        txtApellidoM.setForeground(placeholderColor);
        
        txtNombreCliente.setText(placeholderNombre);
        txtNombreCliente.setForeground(placeholderColor);
        
        txtTelefonoCliente.setText(placeholderTelefono);
        txtTelefonoCliente.setForeground(placeholderColor);
        
        txtCalle.setText(placeholderCalle);
        txtCalle.setForeground(placeholderColor);
        
        txtColonia.setText(placeholderColonia);
        txtColonia.setForeground(placeholderColor);
        
        txtCorreo.setText(placeholderCorreo);
        txtCorreo.setForeground(placeholderColor);
                
        txtMunicipio.setText(placeholderMunicipio);
        txtMunicipio.setForeground(placeholderColor);
        
        txtCiudad.setText(placeholderCiudad);
        txtCiudad.setForeground(placeholderColor);
        
        txtEstado.setText(placeholderEstado);
        txtEstado.setForeground(placeholderColor);
        
        txtCP.setText(placeholderCP);
        txtCP.setForeground(placeholderColor);
        
        txtMarca.setText(placeholderMarca);
        txtMarca.setForeground(placeholderColor);
        
        txtModelo.setText(placeholderModelo);
        txtModelo.setForeground(placeholderColor);
        
        txtTipoCarro.setText(placeholderTipo);
        txtTipoCarro.setForeground(placeholderColor);
        
        txtColorCarro.setText(placeholderColorCarro);
        txtColorCarro.setForeground(placeholderColor);
        
        txtAnioCarro.setText(placeholderAnio);
        txtAnioCarro.setForeground(placeholderColor);
        
        txtEstadoCarro.setText(placeholderEstados);
        txtEstadoCarro.setForeground(placeholderColor);
        
    }
       
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblSolicitudCompra = new javax.swing.JLabel();
        jPanelDatosCliente = new javax.swing.JPanel();
        txtNombreCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        bgDatosComprador = new javax.swing.JPanel();
        lblDatosComprador = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        jPanelDireccion = new javax.swing.JPanel();
        bgDomicilio = new javax.swing.JPanel();
        lblDomicilio = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtCP = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        jPanelCarro = new javax.swing.JPanel();
        bgCarro = new javax.swing.JPanel();
        lblCarro = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtTipoCarro = new javax.swing.JTextField();
        txtColorCarro = new javax.swing.JTextField();
        txtAnioCarro = new javax.swing.JTextField();
        txtEstadoCarro = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(810, 520));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSolicitudCompra.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblSolicitudCompra.setForeground(new java.awt.Color(0, 0, 0));
        lblSolicitudCompra.setText("Solicitud de compra");
        bg.add(lblSolicitudCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanelDatosCliente.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatosCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 0, 57), 3));

        txtNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreClienteFocusLost(evt);
            }
        });
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        txtTelefonoCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoCliente.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtTelefonoCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefonoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoClienteFocusLost(evt);
            }
        });
        txtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });

        bgDatosComprador.setBackground(new java.awt.Color(199, 0, 57));
        bgDatosComprador.setForeground(new java.awt.Color(255, 255, 255));
        bgDatosComprador.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N

        lblDatosComprador.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblDatosComprador.setForeground(new java.awt.Color(255, 255, 255));
        lblDatosComprador.setText("DATOS DEL COMPRADOR");

        javax.swing.GroupLayout bgDatosCompradorLayout = new javax.swing.GroupLayout(bgDatosComprador);
        bgDatosComprador.setLayout(bgDatosCompradorLayout);
        bgDatosCompradorLayout.setHorizontalGroup(
            bgDatosCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDatosCompradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosComprador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgDatosCompradorLayout.setVerticalGroup(
            bgDatosCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDatosCompradorLayout.createSequentialGroup()
                .addComponent(lblDatosComprador)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        txtApellidoP.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoP.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(204, 204, 204));
        txtApellidoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoPFocusLost(evt);
            }
        });
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });

        txtApellidoM.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoM.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(204, 204, 204));
        txtApellidoM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoMFocusLost(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(199, 0, 57));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosClienteLayout = new javax.swing.GroupLayout(jPanelDatosCliente);
        jPanelDatosCliente.setLayout(jPanelDatosClienteLayout);
        jPanelDatosClienteLayout.setHorizontalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgDatosComprador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                        .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDatosClienteLayout.setVerticalGroup(
            jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosClienteLayout.createSequentialGroup()
                .addComponent(bgDatosComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        bg.add(jPanelDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 720, 120));

        jPanelDireccion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 0, 57), 3));

        bgDomicilio.setBackground(new java.awt.Color(199, 0, 57));
        bgDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        bgDomicilio.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N

        lblDomicilio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        lblDomicilio.setText("DOMICILIO");

        javax.swing.GroupLayout bgDomicilioLayout = new javax.swing.GroupLayout(bgDomicilio);
        bgDomicilio.setLayout(bgDomicilioLayout);
        bgDomicilioLayout.setHorizontalGroup(
            bgDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDomicilioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDomicilio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgDomicilioLayout.setVerticalGroup(
            bgDomicilioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgDomicilioLayout.createSequentialGroup()
                .addComponent(lblDomicilio)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        txtMunicipio.setBackground(new java.awt.Color(255, 255, 255));
        txtMunicipio.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtMunicipio.setForeground(new java.awt.Color(204, 204, 204));
        txtMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMunicipioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMunicipioFocusLost(evt);
            }
        });
        txtMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMunicipioActionPerformed(evt);
            }
        });

        txtCalle.setBackground(new java.awt.Color(255, 255, 255));
        txtCalle.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(204, 204, 204));
        txtCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCalleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCalleFocusLost(evt);
            }
        });

        txtColonia.setBackground(new java.awt.Color(255, 255, 255));
        txtColonia.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtColonia.setForeground(new java.awt.Color(204, 204, 204));
        txtColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColoniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColoniaFocusLost(evt);
            }
        });
        txtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColoniaActionPerformed(evt);
            }
        });

        txtEstado.setBackground(new java.awt.Color(255, 255, 255));
        txtEstado.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(204, 204, 204));
        txtEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEstadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEstadoFocusLost(evt);
            }
        });
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(199, 0, 57));

        txtCP.setBackground(new java.awt.Color(255, 255, 255));
        txtCP.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtCP.setForeground(new java.awt.Color(204, 204, 204));
        txtCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFocusLost(evt);
            }
        });

        txtCiudad.setBackground(new java.awt.Color(255, 255, 255));
        txtCiudad.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(204, 204, 204));
        txtCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCiudadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCiudadFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelDireccionLayout = new javax.swing.GroupLayout(jPanelDireccion);
        jPanelDireccion.setLayout(jPanelDireccionLayout);
        jPanelDireccionLayout.setHorizontalGroup(
            jPanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelDireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDireccionLayout.createSequentialGroup()
                        .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(txtColonia)
                        .addContainerGap())
                    .addGroup(jPanelDireccionLayout.createSequentialGroup()
                        .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanelDireccionLayout.setVerticalGroup(
            jPanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDireccionLayout.createSequentialGroup()
                .addComponent(bgDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bg.add(jPanelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 720, 120));

        jPanelCarro.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 0, 57), 3));

        bgCarro.setBackground(new java.awt.Color(199, 0, 57));
        bgCarro.setForeground(new java.awt.Color(255, 255, 255));
        bgCarro.setFont(new java.awt.Font("Roboto", 1, 8)); // NOI18N

        lblCarro.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblCarro.setForeground(new java.awt.Color(255, 255, 255));
        lblCarro.setText("DATOS DEL VEHÍCULO");

        javax.swing.GroupLayout bgCarroLayout = new javax.swing.GroupLayout(bgCarro);
        bgCarro.setLayout(bgCarroLayout);
        bgCarroLayout.setHorizontalGroup(
            bgCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgCarroLayout.setVerticalGroup(
            bgCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgCarroLayout.createSequentialGroup()
                .addComponent(lblCarro)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        txtMarca.setBackground(new java.awt.Color(255, 255, 255));
        txtMarca.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(204, 204, 204));
        txtMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMarcaFocusLost(evt);
            }
        });

        txtModelo.setBackground(new java.awt.Color(255, 255, 255));
        txtModelo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(204, 204, 204));
        txtModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtModeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModeloFocusLost(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(153, 0, 51));
        jSeparator3.setForeground(new java.awt.Color(199, 0, 57));

        txtTipoCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtTipoCarro.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtTipoCarro.setForeground(new java.awt.Color(204, 204, 204));
        txtTipoCarro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoCarroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoCarroFocusLost(evt);
            }
        });
        txtTipoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoCarroActionPerformed(evt);
            }
        });

        txtColorCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtColorCarro.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtColorCarro.setForeground(new java.awt.Color(204, 204, 204));
        txtColorCarro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColorCarroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColorCarroFocusLost(evt);
            }
        });

        txtAnioCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtAnioCarro.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtAnioCarro.setForeground(new java.awt.Color(204, 204, 204));
        txtAnioCarro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnioCarroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAnioCarroFocusLost(evt);
            }
        });
        txtAnioCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioCarroActionPerformed(evt);
            }
        });

        txtEstadoCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtEstadoCarro.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtEstadoCarro.setForeground(new java.awt.Color(204, 204, 204));
        txtEstadoCarro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEstadoCarroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEstadoCarroFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelCarroLayout = new javax.swing.GroupLayout(jPanelCarro);
        jPanelCarro.setLayout(jPanelCarroLayout);
        jPanelCarroLayout.setHorizontalGroup(
            jPanelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCarroLayout.createSequentialGroup()
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txtColorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCarroLayout.createSequentialGroup()
                        .addComponent(txtAnioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(txtEstadoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanelCarroLayout.setVerticalGroup(
            jPanelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarroLayout.createSequentialGroup()
                .addComponent(bgCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bg.add(jPanelCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 720, 120));

        btnContinuar.setBackground(new java.awt.Color(255, 153, 51));
        btnContinuar.setForeground(new java.awt.Color(0, 0, 0));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        bg.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 390, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtAnioCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioCarroActionPerformed

    private void txtMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunicipioActionPerformed

    private void txtApellidoPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoPFocusGained
        // TODO add your handling code here:

        if (txtApellidoP.getText().equals(placeholderApellidoP)) {
                    txtApellidoP.setText("");
                    txtApellidoP.setForeground(normalColor);
                }
            

        
    }//GEN-LAST:event_txtApellidoPFocusGained

    private void txtApellidoPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoPFocusLost
        // TODO add your handling code here:
        if (txtApellidoP.getText().isEmpty()) {
                    txtApellidoP.setText(placeholderApellidoP);
                    txtApellidoP.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtApellidoPFocusLost

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void txtApellidoMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoMFocusGained
        // TODO add your handling code here:
        if (txtApellidoM.getText().equals(placeholderApellidoM)) {
                    txtApellidoM.setText("");
                    txtApellidoM.setForeground(normalColor);
                }
    }//GEN-LAST:event_txtApellidoMFocusGained

    private void txtApellidoMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoMFocusLost
        // TODO add your handling code here:
       
        if (txtApellidoM.getText().isEmpty()) {
                    txtApellidoM.setText(placeholderApellidoM);
                    txtApellidoM.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtApellidoMFocusLost


    private void txtNombreClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreClienteFocusGained
        // TODO add your handling code here:
        if (txtNombreCliente.getText().equals(placeholderNombre)) {
                    txtNombreCliente.setText("");
                    txtNombreCliente.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtNombreClienteFocusGained

    private void txtNombreClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreClienteFocusLost
        // TODO add your handling code here:
        if (txtNombreCliente.getText().isEmpty()) {
                    txtNombreCliente.setText(placeholderNombre);
                    txtNombreCliente.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtNombreClienteFocusLost

    private void txtTelefonoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoClienteFocusGained
        // TODO add your handling code here:
        if ( txtTelefonoCliente.getText().equals(placeholderTelefono)) {
                     txtTelefonoCliente.setText("");
                     txtTelefonoCliente.setForeground(normalColor);
                }
               
       

    }//GEN-LAST:event_txtTelefonoClienteFocusGained

    private void txtTelefonoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoClienteFocusLost
        // TODO add your handling code here:
         if (txtTelefonoCliente.getText().isEmpty()) {
                    txtTelefonoCliente.setText(placeholderTelefono);
                    txtTelefonoCliente.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtTelefonoClienteFocusLost

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        // TODO add your handling code here:
        if (txtCorreo.getText().equals(placeholderCorreo)) {
                    txtCorreo.setText("");
                    txtCorreo.setForeground(normalColor);
                }
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        // TODO add your handling code here:
        if (txtCorreo.getText().isEmpty()) {
                    txtCorreo.setText(placeholderCorreo);
                    txtCorreo.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleFocusGained
        // TODO add your handling code here:
        if (txtCalle.getText().equals(placeholderCalle)) {
                    txtCalle.setText("");
                    txtCalle.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtCalleFocusGained

    private void txtCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCalleFocusLost
        // TODO add your handling code here:
        if (txtCalle.getText().isEmpty()) {
                    txtCalle.setText(placeholderCalle);
                    txtCalle.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtCalleFocusLost

    private void txtColoniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColoniaFocusGained
        // TODO add your handling code here:
        if (txtColonia.getText().equals(placeholderColonia)) {
                    txtColonia.setText("");
                    txtColonia.setForeground(normalColor);
                }

    }//GEN-LAST:event_txtColoniaFocusGained

    private void txtColoniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColoniaFocusLost
        // TODO add your handling code here:
        if (txtColonia.getText().isEmpty()) {
                    txtColonia.setText(placeholderColonia);
                    txtColonia.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtColoniaFocusLost

    private void txtMunicipioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMunicipioFocusGained
        // TODO add your handling code here:
        if (txtMunicipio.getText().equals(placeholderMunicipio)) {
                    txtMunicipio.setText("");
                    txtMunicipio.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtMunicipioFocusGained

    private void txtMunicipioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMunicipioFocusLost
        // TODO add your handling code here:
        if (txtMunicipio.getText().isEmpty()) {
                    txtMunicipio.setText(placeholderMunicipio);
                    txtMunicipio.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtMunicipioFocusLost

    private void txtCiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCiudadFocusGained
        // TODO add your handling code here:
        if (txtCiudad.getText().equals(placeholderCiudad)) {
                    txtCiudad.setText("");
                    txtCiudad.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtCiudadFocusGained

    private void txtCiudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCiudadFocusLost
        // TODO add your handling code here:
        if (txtCiudad.getText().isEmpty()) {
                    txtCiudad.setText(placeholderCiudad);
                    txtCiudad.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtCiudadFocusLost

    private void txtEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEstadoFocusGained
        // TODO add your handling code here:
        if (txtEstado.getText().equals(placeholderEstado)) {
                    txtEstado.setText("");
                    txtEstado.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtEstadoFocusGained

    private void txtEstadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEstadoFocusLost
        // TODO add your handling code here:
        if (txtEstado.getText().isEmpty()) {
                    txtEstado.setText(placeholderEstado);
                    txtEstado.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtEstadoFocusLost

    private void txtCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFocusGained
        // TODO add your handling code here:
        if (txtCP.getText().equals(placeholderCP)) {
                    txtCP.setText("");
                    txtCP.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtCPFocusGained

    private void txtCPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFocusLost
        // TODO add your handling code here:
        if (txtCP.getText().isEmpty()) {
                    txtCP.setText(placeholderCP);
                    txtCP.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtCPFocusLost

    private void txtMarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMarcaFocusGained
        // TODO add your handling code here:
        if (txtMarca.getText().equals(placeholderMarca)) {
                    txtMarca.setText("");
                    txtMarca.setForeground(normalColor);
                }
       
    }//GEN-LAST:event_txtMarcaFocusGained

    private void txtMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMarcaFocusLost
        // TODO add your handling code here:
         if (txtMarca.getText().isEmpty()) {
                    txtMarca.setText(placeholderMarca);
                    txtMarca.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtMarcaFocusLost

    private void txtModeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModeloFocusGained
        // TODO add your handling code here:
        if (txtModelo.getText().equals(placeholderModelo)) {
                    txtModelo.setText("");
                    txtModelo.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtModeloFocusGained

    private void txtModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModeloFocusLost
        // TODO add your handling code here:
        if (txtModelo.getText().isEmpty()) {
                    txtModelo.setText(placeholderModelo);
                    txtModelo.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtModeloFocusLost

    private void txtTipoCarroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoCarroFocusGained
        // TODO add your handling code here:
        if (txtTipoCarro.getText().equals(placeholderTipo)) {
                    txtTipoCarro.setText("");
                    txtTipoCarro.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtTipoCarroFocusGained

    private void txtTipoCarroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoCarroFocusLost
        // TODO add your handling code here:
        if (txtTipoCarro.getText().isEmpty()) {
                    txtTipoCarro.setText(placeholderTipo);
                    txtTipoCarro.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtTipoCarroFocusLost

    private void txtColorCarroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorCarroFocusGained
        // TODO add your handling code here:
        if (txtColorCarro.getText().equals(placeholderColorCarro)) {
                    txtColorCarro.setText("");
                    txtColorCarro.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtColorCarroFocusGained

    private void txtColorCarroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorCarroFocusLost
        // TODO add your handling code here:
        if (txtColorCarro.getText().isEmpty()) {
                    txtColorCarro.setText(placeholderColorCarro);
                    txtColorCarro.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtColorCarroFocusLost

    private void txtAnioCarroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioCarroFocusGained
        // TODO add your handling code here:
        if (txtAnioCarro.getText().equals(placeholderAnio)) {
                    txtAnioCarro.setText("");
                    txtAnioCarro.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtAnioCarroFocusGained

    private void txtAnioCarroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnioCarroFocusLost
        // TODO add your handling code here:
        if (txtAnioCarro.getText().isEmpty()) {
                    txtAnioCarro.setText(placeholderAnio);
                    txtAnioCarro.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtAnioCarroFocusLost

    private void txtEstadoCarroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEstadoCarroFocusGained
        // TODO add your handling code here:
        if (txtEstadoCarro.getText().equals(placeholderEstados)) {
                    txtEstadoCarro.setText("");
                    txtEstadoCarro.setForeground(normalColor);
                }
        
    }//GEN-LAST:event_txtEstadoCarroFocusGained

    private void txtEstadoCarroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEstadoCarroFocusLost
        // TODO add your handling code here:
        if (txtEstadoCarro.getText().isEmpty()) {
                    txtEstadoCarro.setText(placeholderEstados);
                    txtEstadoCarro.setForeground(placeholderColor);
                }
    }//GEN-LAST:event_txtEstadoCarroFocusLost

    private void txtTipoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoCarroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTipoCarroActionPerformed

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        cliente.setApellidoP(txtApellidoP.getText());
        cliente.setApellidoM(txtApellidoM.getText());
        cliente.setNombre(txtNombreCliente.getText());
        cliente.setTelefono(Long.parseLong(txtTelefonoCliente.getText()));
        cliente.setCorreo(txtCorreo.getText());
        
        cliente.setCalle(txtCalle.getText());
        cliente.setColonia(txtColonia.getText());
        cliente.setMunicipio(txtMunicipio.getText());
        cliente.setCiudad(txtCiudad.getText());
        cliente.setEstado(txtEstado.getText());
        cliente.setCP(txtCP.getText());
        
        /*
        cliente.setMarca(txtMarca.getText());
        cliente.setModelo(txtModelo.getText());
        cliente.setTipoCarro(txtTipoCarro.getText());
        cliente.setColorCarro(txtColorCarro.getText());
        cliente.setAño(Integer.parseInt(txtAnioCarro.getText()));
        cliente.setCorreo(txtEstadoCarro.getText());
   */
       
        ClienteDB dao = new ClienteDB();
      
        if (dao.RegistrarClientes(cliente)){
            JOptionPane.showMessageDialog(this, "Cliente registrado con éxito");
            //limpiarCampos();
            
        }else {
            JOptionPane.showMessageDialog(this, "Error al registrar cliente");
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void txtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColoniaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgCarro;
    private javax.swing.JPanel bgDatosComprador;
    private javax.swing.JPanel bgDomicilio;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JPanel jPanelCarro;
    private javax.swing.JPanel jPanelDatosCliente;
    private javax.swing.JPanel jPanelDireccion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblDatosComprador;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblSolicitudCompra;
    private javax.swing.JTextField txtAnioCarro;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtColorCarro;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstadoCarro;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTipoCarro;
    // End of variables declaration//GEN-END:variables
}
